name: domain_interface_explorer
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - numpy
  - numba
  - scikit-learn
  - opentsne
  - pynndescent
  - annoy
  - tqdm
  - hdbscan
  - pymol-open-source
