from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]


DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
DEFAULT_INTERFACE_DIR = PROJECT_ROOT / "data"
DEFAULT_CACHE_DIR = PROJECT_ROOT / "cache"
DEFAULT_CACHE_WORKERS = 4
STATIC_DIR = PROJECT_ROOT / "domain_interface_explorer" / "static"
ALPHAFOLD_API = "https://alphafold.ebi.ac.uk/api/prediction/{accession}"
SELECTOR_STATS_CACHE_VERSION = "7"
PFAM_METADATA_CACHE_VERSION = "1"
INTERPRO_PFAM_LIST_API = "https://www.ebi.ac.uk/interpro/api/entry/all/pfam/?format=json&page_size=200"
PFAM_METADATA_REFRESH_MAX_AGE_SECONDS = 14 * 24 * 60 * 60
PFAM_INFO_CACHE_VERSION = "1"
INTERPRO_PFAM_ENTRY_API = "https://www.ebi.ac.uk/interpro/api/entry/pfam/{accession}/?format=json"
INTERPRO_PFAM_ENTRY_PAGE = "https://www.ebi.ac.uk/interpro/entry/pfam/{accession}/"
PFAM_INFO_REFRESH_MAX_AGE_SECONDS = 30 * 24 * 60 * 60
EMBEDDING_CACHE_VERSION = "4"
CLUSTERING_CACHE_VERSION = "8"
HIERARCHY_CACHE_VERSION = "2"
DEFAULT_TSNE_LEARNING_RATE = "auto"
DEFAULT_TSNE_MAX_ITER = 1000
DEFAULT_TSNE_EARLY_EXAGGERATION_ITER = 250
DEFAULT_TSNE_EARLY_EXAGGERATION = 12.0
DEFAULT_TSNE_NEIGHBORS = "approx"
DEFAULT_TSNE_THETA = 0.5
DEFAULT_TSNE_RANDOM_STATE = 42
DEFAULT_EMBEDDING_METHOD = "pca"
DEFAULT_EMBEDDING_DISTANCE = "binary"
DEFAULT_DISTANCE_METRIC = "overlap"
DEFAULT_CLUSTER_MIN_SIZE = 25
DEFAULT_CLUSTER_SELECTION_EPSILON = 0.25
DEFAULT_CLUSTERING_METHOD = "hierarchical"
DEFAULT_HIERARCHICAL_LINKAGE = "average"
DEFAULT_HIERARCHICAL_TARGET = "distance_threshold"
DEFAULT_HIERARCHICAL_N_CLUSTERS = 8
DEFAULT_HIERARCHICAL_DISTANCE_THRESHOLD = 0.5
DEFAULT_HIERARCHICAL_PERSISTENCE_MIN_LIFETIME = 0.05
DEFAULT_HIERARCHICAL_PERSISTENCE_LIFETIME_WEIGHT = 0.5
DEFAULT_HIERARCHICAL_PERSISTENCE_SCORE_MODE = "rectangle"
DEFAULT_HIERARCHICAL_MIN_CLUSTER_SIZE = 10
DEFAULT_CLUSTER_COMPARE_LIMIT = 9
DEFAULT_MIN_INTERFACE_SIZE = 5
DISTANCE_DATA_CACHE_LIMIT = 8
INTERFACE_DISTANCE_CACHE_VERSION = "1"
