export const CELL_WIDTH = 12;
export const ROW_HEIGHT = 18;
export const HEADER_HEIGHT = 42;
export const LABEL_WIDTH = 240;
export const TEXT_FONT = '12px "Iosevka Web", "IBM Plex Mono", monospace';

export const DEFAULT_EMBEDDING_SETTINGS = {
  method: "pca",
  distance: "binary",
  perplexity: "auto",
  learningRate: "auto",
  maxIter: 1000,
  earlyExaggerationIter: 250,
  earlyExaggeration: 12.0,
  neighbors: "approx",
  theta: 0.5,
};

export const DEFAULT_CLUSTERING_SETTINGS = {
  method: "hierarchical",
  distance: "overlap",
  minClusterSize: 25,
  minSamples: "",
  hdbscanEffectiveMinSamples: "",
  clusterSelectionEpsilon: 0.25,
  hdbscanSampleScope: "expanded",
  linkage: "average",
  hierarchicalTarget: "distance_threshold",
  nClusters: "",
  distanceThreshold: 0.5,
  persistenceMinLifetime: 0.05,
  persistenceLifetimeWeight: 0.5,
  persistenceScoreMode: "rectangle",
  hierarchicalMinClusterSize: 10,
  domainSizeMin: "",
  domainSizeMax: "",
  pfamRowCoverageMin: "",
  pfamRowCoverageMax: "",
};

export const DEFAULT_SELECTION_SETTINGS = {
  minInterfaceSize: 5,
};

export const DEFAULT_STRUCTURE_DISPLAY_VIEW_PRESETS = {
  structure: "current",
  representative: "current",
  clusterCompare: "current",
  clusterOverview: "current",
};

export const DEFAULT_STRUCTURE_DISPLAY_SETTINGS = {
  preset: "soft",
  background: "#fdfcf8",
  cameraMode: "perspective",
  fieldOfView: 45,
  clipFocusRadius: 0,
  clipFar: false,
  clipMinNear: 0.01,
  illumination: false,
  illuminationMaxIterations: 8,
  illuminationRendersPerFrameMin: 1,
  illuminationRendersPerFrameMax: 16,
  illuminationTargetFps: 30,
  illuminationSteps: 32,
  illuminationRefineSteps: 4,
  illuminationBounces: 4,
  illuminationDenoise: true,
  illuminationDenoiseMin: 0.15,
  illuminationDenoiseMax: 1,
  illuminationIgnoreOutline: true,
  ambientOcclusion: true,
  antialiasing: "smaa",
  antialiasSampleLevel: 3,
  smaaEdgeThreshold: 0.1,
  smaaMaxSearchSteps: 16,
  fxaaEdgeThresholdMin: 0.0312,
  fxaaEdgeThresholdMax: 0.063,
  fxaaIterations: 12,
  fxaaSubpixelQuality: 0.3,
  occlusionStrength: 0.8,
  aoRadius: 5,
  aoSamples: 32,
  aoResolutionScale: 1,
  aoBlurKernelSize: 15,
  shadows: false,
  shadowDistance: 4,
  shadowSteps: 2,
  shadowTolerance: 1,
  outline: false,
  outlineScale: 1,
  outlineThreshold: 0.33,
  outlineColor: "#1e1b17",
  outlineTransparent: true,
  depthOfField: false,
  dofBlur: 8,
  dofBlurSpread: 1,
  dofFocusOffset: 0,
  dofFocusRange: 28,
  dofFocusTarget: "camera-target",
  dofFocusMode: "sphere",
  fog: false,
  fogIntensity: 18,
  sharpen: false,
  sharpenStrength: 0.35,
  sharpenDenoise: true,
  bloom: false,
  bloomStrength: 0.65,
  bloomRadius: 0.18,
  bloomThreshold: 0.82,
  bloomMode: "luminosity",
  exposure: 1.0,
  ambientIntensity: 0.48,
  lightIntensity: 0.82,
  highlightStrength: 0.42,
  highlightColor: "#f3c14f",
  contextAlpha: 0.24,
  representativeClusterSupportMin: 4,
  clusterOverviewClusterSupportMin: 0,
  combineSameStyleRegions: false,
  restProteinStyle: "cartoon",
  restProteinColor: "#c7c3bc",
  restProteinAlpha: 0.24,
  mainDomainStyle: "cartoon",
  mainDomainColor: "#8f8a82",
  mainDomainAlpha: 1,
  mainSurfaceStyle: "cartoon",
  mainSurfaceColor: "#d7a84c",
  mainSurfaceAlpha: 1,
  mainInterfaceStyle: "cartoon",
  mainInterfaceColor: "#bc402d",
  mainInterfaceAlpha: 1,
  partnerDomainStyle: "cartoon",
  partnerDomainColor: "#b8c9dc",
  partnerDomainAlpha: 1,
  partnerSurfaceStyle: "cartoon",
  partnerSurfaceColor: "#5b9fe3",
  partnerSurfaceAlpha: 1,
  partnerInterfaceStyle: "cartoon",
  partnerInterfaceColor: "#0b3f78",
  partnerInterfaceAlpha: 1,
  contactLinesVisible: true,
  contactColor: "#4f4f4f",
  contactOpacity: 0.6,
  contactRadius: 0.06,
  plipInteractionsVisible: true,
  plipInteractionOpacity: 0.9,
  plipInteractionRadius: 0.14,
  cartoonSizeFactor: 0.2,
  cartoonAspectRatio: 5,
  cartoonArrowFactor: 1.5,
  cartoonTubularHelices: false,
  cartoonRoundCaps: false,
  cartoonHelixProfile: "elliptical",
  cartoonNucleicProfile: "square",
  cartoonLinearSegments: 8,
  cartoonRadialSegments: 16,
  cartoonDetail: 0,
  surfaceResolution: 0.5,
  surfaceProbeRadius: 1.4,
  surfaceProbePositions: 36,
  surfaceColorSmoothing: "auto",
  surfaceColorSmoothingResolutionFactor: 2,
  surfaceColorSmoothingSampleStride: 3,
  roughness: 0.72,
  metalness: 0,
  bumpiness: 0.08,
  quality: "auto",
};

export const THREE_TO_ONE = {
  ALA: "A",
  ARG: "R",
  ASN: "N",
  ASP: "D",
  CYS: "C",
  GLN: "Q",
  GLU: "E",
  GLY: "G",
  HIS: "H",
  ILE: "I",
  LEU: "L",
  LYS: "K",
  MET: "M",
  PHE: "F",
  PRO: "P",
  SER: "S",
  THR: "T",
  TRP: "W",
  TYR: "Y",
  VAL: "V",
  SEC: "U",
  PYL: "O",
  ASX: "B",
  GLX: "Z",
  XLE: "J",
  UNK: "X",
};

export const PARTNER_COLOR_PALETTE = [
  "#b4493a",
  "#2b6cb0",
  "#c7871a",
  "#2f855a",
  "#7b5ea7",
  "#b85c8e",
  "#008b8b",
  "#8a5a44",
  "#d94841",
  "#4c78a8",
  "#b279a2",
  "#a0a43c",
  "#e07a1f",
  "#5c8f29",
  "#795548",
  "#2a9d8f",
];

export const CLUSTER_COLOR_PALETTE = [
  "#3f6ba5",
  "#b2553f",
  "#2f7d5c",
  "#9b6bb3",
  "#c18820",
  "#b35b84",
  "#4a8c8c",
  "#7a5d45",
  "#d2663d",
  "#6d8a2b",
  "#456ccf",
  "#9f4d2d",
];
